# Generated by Django 2.1.2 on 2018-12-01 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20181130_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_response', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=140)),
                ('group', models.CharField(max_length=5)),
                ('archive', models.FileField(upload_to='')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
